document.addEventListener('DOMContentLoaded', () => {
    const generateBtn = document.getElementById('generate-btn');
    const resultSection = document.getElementById('result-section');
    const rawResumeCode = document.getElementById('raw-resume');
    const rawCoverCode = document.getElementById('raw-cover');
    const dlResumeBtn = document.getElementById('download-resume');
    const dlCoverBtn = document.getElementById('download-cover-letter');

    generateBtn.addEventListener('click', async () => {
        const fullName = document.getElementById('full-name').value.trim();
        const contactInfo = document.getElementById('contact-info').value.trim();
        const linkedinUrl = document.getElementById('linkedin-url').value.trim();
        const githubUrl = document.getElementById('github-url').value.trim();
        const experience = document.getElementById('experience').value.trim();
        const education = document.getElementById('education').value.trim();
        const jobTitle = document.getElementById('job-title').value.trim();
        const companyName = document.getElementById('company-name').value.trim();
        const jobDescription = document.getElementById('job-description').value.trim();

        if (!fullName || !experience || !jobTitle) {
            alert('Please fill out the essential fields (Name, Experience, Job Title).');
            return;
        }

        // UI Loading State
        generateBtn.classList.add('loading');
        generateBtn.querySelector('.btn-text').textContent = 'Generating... (This may take up to 30s)';
        generateBtn.querySelector('.fa-wand-magic-sparkles').classList.add('hidden');
        generateBtn.querySelector('.loader-spinner').classList.remove('hidden');
        resultSection.classList.add('hidden');

        try {
            // Call the local Python Backend
            const response = await fetch('http://localhost:5000/api/generate', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    fullName,
                    contactInfo,
                    linkedinUrl,
                    githubUrl,
                    experience,
                    education,
                    jobTitle,
                    companyName,
                    jobDescription
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to generate documents from the server.');
            }

            // Update UI
            rawResumeCode.textContent = data.resume_latex;
            rawCoverCode.innerHTML = data.cover_html;

            // Use the PDF URLs generated by the backend
            dlResumeBtn.href = data.resume_pdf_url;

            // Generate a downloadable HTML document for the cover letter
            const blob = new Blob([data.cover_html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            dlCoverBtn.href = url;
            dlCoverBtn.download = "Cover_Letter.html";

            resultSection.classList.remove('hidden');

            // Scroll to results smoothly
            resultSection.scrollIntoView({ behavior: 'smooth' });

        } catch (error) {
            alert(`Error: ${error.message}`);
        } finally {
            generateBtn.classList.remove('loading');
            generateBtn.querySelector('.btn-text').textContent = 'Generate LaTeX PDF Docs';
            generateBtn.querySelector('.fa-wand-magic-sparkles').classList.remove('hidden');
            generateBtn.querySelector('.loader-spinner').classList.add('hidden');
        }
    });
});
